In [44]:
#Import library numpy, pandas dan sclikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [45]:
#Membaca dataset dari file ke pandas dataFrame
irisDataset = pd.read_csv('klasifikasi_dataset_iris.csv', delimiter=';', header=0)

In [46]:
irisDataset.head()

Id  SepalLengthCm  ...  PetalWidthCm          Species
0   1              6  ...            22  Iris-versicolor
1   2             12  ...             7  Iris-versicolor
2   3             19  ...            11  Iris-versicolor
3   4             12  ...            23  Iris-versicolor
4   5             19  ...            10  Iris-versicolor

[5 rows x 6 columns]

In [47]:
#mengubah kelas (kolom "species") dari string ke unique-integer
irisDataset["Species"] = pd.factorize(irisDataset.Species)[0]

In [48]:
irisDataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1              6             6              3            22        0
1   2             12            20              6             7        0
2   3             19             5              4            11        0
3   4             12            18              4            23        0
4   5             19            13             14            10        0

In [49]:
print(irisDataset)

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0     1              6             6              3            22        0
1     2             12            20              6             7        0
2     3             19             5              4            11        0
3     4             12            18              4            23        0
4     5             19            13             14            10        0
..  ...            ...           ...            ...           ...      ...
95   96              3            15              7            13        1
96   97              7             9             10             7        1
97   98              7             6             14            13        1
98   99             14            10             18             8        1
99  100             13            23             12            18        1

[100 rows x 6 columns]


In [50]:
#menghapus kolom "id"
irisDataset = irisDataset.drop(labels="Id", axis=1)

In [51]:
print(irisDataset)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0               6             6              3            22        0
1              12            20              6             7        0
2              19             5              4            11        0
3              12            18              4            23        0
4              19            13             14            10        0
..            ...           ...            ...           ...      ...
95              3            15              7            13        1
96              7             9             10             7        1
97              7             6             14            13        1
98             14            10             18             8        1
99             13            23             12            18        1

[100 rows x 5 columns]


In [52]:
#mengubah dataframe ke array numpy
irisDataset = irisDataset.to_numpy()

In [53]:
print(irisDataset)

[[ 6  6  3 22  0]
 [12 20  6  7  0]
 [19  5  4 11  0]
 [12 18  4 23  0]
 [19 13 14 10  0]
 [ 7 11 10 15  0]
 [19 18 17 25  0]
 [20 10 21 11  0]
 [ 3  7 14  7  0]
 [10 18 10 26  0]
 [ 8 20 13 12  0]
 [10 17  9 26  0]
 [19  8 20 17  0]
 [11 16 12  8  0]
 [19 24 19  7  0]
 [ 9 14  6 22  0]
 [13 15 13 18  0]
 [ 7 16  6 26  0]
 [11 24 16 23  0]
 [ 8 21  3 20  0]
 [ 7 11 11  7  0]
 [ 5 20 14 16  0]
 [20  9  8 19  0]
 [18 23  5 11  0]
 [ 6 19 15 19  0]
 [ 7 15 11 17  0]
 [19 14 18 10  0]
 [ 4 11 10 23  0]
 [ 2 11 12  9  0]
 [ 4 13  7  7  0]
 [17 13 10 12  0]
 [20 22 15 17  0]
 [ 4  5 20 11  0]
 [14 23  3 26  0]
 [13 13 16 12  0]
 [19  9 13 10  0]
 [19  8  8  8  0]
 [16 22 11 11  0]
 [ 7 12  8 12  0]
 [10 19 13 15  0]
 [12 23  8 17  0]
 [10 16 15 18  0]
 [ 9 11 17 13  0]
 [14 23  7 18  0]
 [ 5 20 12 21  0]
 [14 20 15  9  0]
 [ 7 22  8 21  0]
 [12 18 13 16  0]
 [16 16  6  9  0]
 [ 4 10 16  9  0]
 [ 5 21 19  7  1]
 [20 18  7 12  1]
 [14 24  8 15  1]
 [ 5 17 10 13  1]
 [11 24  4 26  1]
 [17 25 11

In [54]:
#membagi dataset => 80 baris data untuk training dan 20 baris data untuk testing
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]), axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]), axis=0)                              

In [55]:
print(dataTraining)
len(dataTraining)

[[ 6  6  3 22  0]
 [12 20  6  7  0]
 [19  5  4 11  0]
 [12 18  4 23  0]
 [19 13 14 10  0]
 [ 7 11 10 15  0]
 [19 18 17 25  0]
 [20 10 21 11  0]
 [ 3  7 14  7  0]
 [10 18 10 26  0]
 [ 8 20 13 12  0]
 [10 17  9 26  0]
 [19  8 20 17  0]
 [11 16 12  8  0]
 [19 24 19  7  0]
 [ 9 14  6 22  0]
 [13 15 13 18  0]
 [ 7 16  6 26  0]
 [11 24 16 23  0]
 [ 8 21  3 20  0]
 [ 7 11 11  7  0]
 [ 5 20 14 16  0]
 [20  9  8 19  0]
 [18 23  5 11  0]
 [ 6 19 15 19  0]
 [ 7 15 11 17  0]
 [19 14 18 10  0]
 [ 4 11 10 23  0]
 [ 2 11 12  9  0]
 [ 4 13  7  7  0]
 [17 13 10 12  0]
 [20 22 15 17  0]
 [ 4  5 20 11  0]
 [14 23  3 26  0]
 [13 13 16 12  0]
 [19  9 13 10  0]
 [19  8  8  8  0]
 [16 22 11 11  0]
 [ 7 12  8 12  0]
 [10 19 13 15  0]
 [ 5 21 19  7  1]
 [20 18  7 12  1]
 [14 24  8 15  1]
 [ 5 17 10 13  1]
 [11 24  4 26  1]
 [17 25 11 10  1]
 [10 22 11 15  1]
 [19 15  3  9  1]
 [12 11 19 12  1]
 [ 5 22 21 26  1]
 [ 3 15 12 26  1]
 [ 2 17 13 10  1]
 [ 9 16 18 20  1]
 [20  6 10 19  1]
 [19 19 14 10  1]
 [10 12 18

80

In [56]:
print(dataTesting)
len(dataTesting)

[[12 23  8 17  0]
 [10 16 15 18  0]
 [ 9 11 17 13  0]
 [14 23  7 18  0]
 [ 5 20 12 21  0]
 [14 20 15  9  0]
 [ 7 22  8 21  0]
 [12 18 13 16  0]
 [16 16  6  9  0]
 [ 4 10 16  9  0]
 [11 19 15 13  1]
 [ 7 25  8 13  1]
 [15 16 21 22  1]
 [17  5  3 26  1]
 [ 6 11  8 21  1]
 [ 3 15  7 13  1]
 [ 7  9 10  7  1]
 [ 7  6 14 13  1]
 [14 10 18  8  1]
 [13 23 12 18  1]]


20

In [57]:
#memecah dataset ke input label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]
print(labelTraining)
len(labelTraining)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1]


80

In [58]:
#mendefinisikan decision tree classifier
model = tree.DecisionTreeClassifier()

In [59]:
#mentraining model
model = model.fit(inputTraining, labelTraining)

In [60]:
#memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
Hasil Prediksi :  [1 0 1 1 0 1 0 0 0 1 1 1 1 0 0 1 0 0 1 1]


In [61]:
#menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 11 data
Prediksi Salah : 9 data
Akurasi : 55.00000000000001 %
